export const MOTIVATIONAL_QUOTES = [
  "Wellness is built in the choices you repeat gently.",
  "Small resets still count as progress.",
  "Protect your attention before you spend it.",
  "A calmer body makes clearer decisions.",
  "One grounded choice can change the whole afternoon.",
  "The next useful step matters more than the perfect plan.",
  "You are allowed to slow down and still move forward.",
  "Pause, breathe, and return with intention.",
  "Momentum grows from repetition, not intensity.",
  "Calm effort compounds.",
  "Make the next ten minutes honest and simple.",
  "Your focus improves when your body feels supported.",
  "Tiny routines create reliable energy.",
  "Rest is part of disciplined work.",
  "A clear mind starts with one finished task.",
  "You do not need urgency to make progress.",
  "Drink water, reset posture, keep moving.",
  "Consistency feels quiet while it is working.",
  "Protect the habit, and the results will follow.",
  "Attention is a resource. Spend it on purpose.",
  "Steady effort beats dramatic starts.",
  "A short break can rescue a long day.",
  "Let today be useful, not overloaded.",
  "Better rhythm, better work.",
  "Focus is easier when the next step is obvious.",
  "A calmer pace can still be ambitious.",
  "Return to the work without punishing yourself.",
  "The simplest plan is often the one you will keep.",
  "Breathe before you react.",
  "Lower the friction, raise the follow-through.",
  "A good day is built from recoveries.",
  "You can reset without starting over.",
  "Protecting your energy is productive.",
  "The goal is sustainable momentum.",
  "A useful task completed beats five tasks circling.",
  "Quiet progress still counts.",
  "Make room for clarity, then act.",
  "Good focus begins with good boundaries.",
  "Choose the next right action and start there.",
  "Your system matters more than your mood.",
  "Short sessions done well add up fast.",
  "Hydrate, breathe, continue.",
  "Relax your shoulders. Your mind will follow.",
  "Small acts of care improve deep work.",
  "Recovering your attention is a win.",
  "Less noise, more intention.",
  "Stress softens when the next step is simple.",
  "Consistency is built in ordinary minutes.",
  "The reset is part of the routine.",
  "Structure makes discipline easier.",
  "A focused hour starts with a settled mind.",
  "You can do meaningful work at a humane pace.",
  "The best restart is the one you take now.",
  "Guard your energy like it matters. It does.",
  "Better boundaries create better output.",
  "Today does not need to be perfect to be productive.",
  "Finish one thing with care.",
  "Use reminders as support, not pressure.",
  "Stillness can sharpen action.",
  "Build a day your future self can trust.",
  "Steady beats scattered.",
  "Take care of the human doing the work.",
  "A brief pause can restore direction.",
  "Make focus gentle enough to repeat.",
  "Progress likes a calm nervous system."
];

export function getRandomQuote() {
  const index = Math.floor(Math.random() * MOTIVATIONAL_QUOTES.length);
  return MOTIVATIONAL_QUOTES[index];
}
